import os
from time import sleep
from colorama import Fore
os.system("clear")
print("🌹🍃🌹🍃🌹")
sleep(0.2)
print("🍃.•°``°•.¸.•°``°•.🍃")
sleep(0.2)
print("🌹ANDRO  💛 NUX  💛 🌹")
sleep(0.2)
print("🍃`•.¸ ¸.•` 🍃")
sleep(0.2)
print("🌹° •.¸¸.•° 🌹")
sleep(0.2)
print("┏━━━━  ━━━  ━━━━━┓")
sleep(0.2)
print("♦ Phone Pyae Thu ♦")
sleep(0.2)
print("┗━━━━  ━━━  ━━━━━┛")
sleep(0.2)
print("┊┊┊┊┊\n┊┊┊┊💚\n┊┊┊💙 \n┊┊💛\n┊💜\n♥️")
sleep(1)
print("╭━━━━━━━╮\n┃  ● ══ ┃\n┃███████┃  🇦​🇳​🇩​🇷​🇴\n┃███████┃\n┃███████┃  🇳​🇺​🇽​\n┃███████┃\n┃███████┃\n┃███████┃\n┃   ○   ┃\n╰━━━━━━━╯\n", end="")
sleep(0.5)
print(Fore.RED + "Coder       ☣☣ Phone Pyae Thu")
sleep(0.5)
print(Fore.GREEN + "FaceBook acc☣☣ https://www.facebook.com/Phone.Pyae.Thu.Kitaro")
sleep(0.5)
print(Fore.BLUE + "Github      ☣☣ https://www.github.com/Phone.Pyae.Thu")
sleep(0.5)
print(Fore.YELLOW + "Note!☣! It can take too long time! and can use too many of your data and Disk")
sleep(0.5)
print(Fore.RED + "--------------------------------")
print("🎲1.Kali" ,end="        ")
print("🎲2.Kali Nethunter")
print("🎲3.Ubuntu" ,end="      ")
print("🎲4.Debian")
print("🎲5.BackBox" ,end="     ")
print("🎲6.Black Arch")
print("🎲7.Arch Linux" ,end="  ")
print("🎲8.Fedora")
print("🎲9.CentOs" ,end="      ")
print("🎲10.Void Linux")
print("🎲11.Alpine" ,end="     ")
print("🎲12.Exit")
print(Fore.GREEN + ">>>Select One<<<")
S = input("(☣)▓▓▓⫸⫸  ")
if S == "1":
    print(Fore.RED + "Wait.It may be take a long time")
    sleep(2)
    print(Fore.BLUE + "Installing . . . . ")
    sleep(0.5)
    os.system("pkg install wget openssl-tool proot -y && hash -r")
    os.system("wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Kali/kali.sh && bash kali.sh")
    print(Fore.GREEN + "type ./start-kali.sh to run kali")
elif S == "2":
	print(Fore.RED + "Wait.It may be take a long time")
	sleep(2)
	print(Fore.BLUE + "Installing . . . . ")
	sleep(0.5)
	os.system("pkg install wget openssl-tool proot -y && hash -r")
	os.system("wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Nethunter/nethunter.sh && bash nethunter.sh")
	print(Fore.GREEN + "type ./start-nethunter.sh to run nethunter")
elif S == "3":
	print(Fore.RED + "Wait.It may be take a long time")
	sleep(2)
	print(Fore.BLUE + "Installing . . . . ")
	sleep(0.5)
	os.system("pkg install wget openssl-tool proot -y && hash -r")
	os.system("wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh && bash ubuntu.sh")
	print(Fore.GREEN + "type ./start-ubuntu.sh to run ubuntu")
elif S == "4":
	print(Fore.RED + "Wait.It may be take a long time")
	sleep(2)
	print(Fore.BLUE + "Installing . . . . ")
	sleep(0.5)
	os.system("pkg install wget openssl-tool proot -y && hash -r")
	os.system("wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Debian/debian.sh && bash debian.sh")
	print(Fore.GREEN + "type ./start-debian.sh to run debian")
elif S == "5":
	print(Fore.RED + "Wait.It may be take a long time")
	sleep(2)
	print(Fore.BLUE + "Installing . . . . ")
	sleep(0.5)
	os.system("pkg install wget openssl-tool proot -y && hash -r")
	os.system("wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/BackBox/backbox.sh && bash backbox.sh")
	os.system("cd")
	os.system("./start-arch.sh")
	os.system("chmod 755 additional.sh && ./additional.sh")
elif S == "6":
	print(Fore.RED + "BlackArch can run only in Arch Linux")
	print(Fore.GREEN + "So U must install Arch Linux")
	print(Fore.YELLOW + "1. I have Arch Linux so run in Arch Linux")
	print(Fore.YELLOW + "2. I haven't Arch Linux so install first")
	x = input("select one >>")
	if x == "1":
				os.system("cd")
				os.system("./start-arch.sh")
				os.system("pacman-key --init && pacman-key --populate archlinuxarm && pacman -Sy --noconfirm curl && curl -O https://blackarch.org/strap.sh && chmod +x strap.sh && ./strap.sh")
	elif x == "2":
	   print(Fore.RED + "Wait.It may be take a long time")
	   sleep(2)
	   print(Fore.RED + "Arch Linux may be error")
	   sleep(2)
	   print(Fore.BLUE + "Installing . . . . ")
	   sleep(0.5)
	   os.system("pkg install wget openssl-tool proot -y && hash -r")
	   os.system("wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Arch/armhf/arch.sh && bash arch.sh")
	   os.system("cd")
	   os.system("./start-arch.sh")
	   os.system("chmod 755 additional.sh && ./additional.sh")
elif S == "7":
    print(Fore.RED + "Wait.It may be take a long time")
    sleep(2)
    print(Fore.RED + "Arch Linux may be error")
    sleep(2)
    print(Fore.BLUE + "Installing . . . . ")
    sleep(0.5)
    os.system("pkg install wget openssl-tool proot -y && hash -r")
    os.system("wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Arch/armhf/arch.sh && bash arch.sh")
    print(Fore.GREEN + "type ./start-arch.sh to run arch")
elif S == "8":
    print(Fore.RED + "Wait.It may be take a long time")
    sleep(2)
    print(Fore.BLUE + "Installing . . . . ")
    sleep(0.5)
    os.system("pkg install wget openssl-tool proot -y && hash -r")
    os.system("wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Fedora/fedora.sh && bash fedora.sh")
    print(Fore.GREEN + "type ./start-fedora.sh to run fedora")
elif S == "9":
    print(Fore.RED + "Wait.It may be take a long time")
    sleep(2)
    print(Fore.BLUE + "Installing . . . . ")
    sleep(0.5)
    os.system("pkg install wget openssl-tool proot -y && hash -r")
    os.system("wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/CentOS/centos.sh && bash centos.sh")
    print(Fore.GREEN + "type ./start-centos.sh to run centos")
elif S == "10":
    print(Fore.RED + "Wait.It may be take a long time")
    sleep(2)
    print(Fore.BLUE + "Installing . . . . ")
    sleep(0.5)
    os.system("pkg install wget openssl-tool proot -y && hash -r")
    os.system("wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Void/void.sh && bash void.sh")
    print(Fore.GREEN + "type ./start-void.sh to run void")
elif S == "11":
    print(Fore.RED + "Wait.It may be take a long time")
    sleep(2)
    print(Fore.BLUE + "Installing . . . . ")
    sleep(0.5)
    os.system("pkg install wget openssl-tool proot -y && hash -r")
    os.system("wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Alpine/alpine.sh && bash alpine.sh")
    print(Fore.GREEN + "type ./start-alpine.sh to run alpine")
elif S == "12":
	os.system("exit")